### PR TITLE
added tests for assignment 1

### PR DESCRIPTION
**Pull request by julwil**

### CODE REVIEW

**Review by jvdassen — APPROVED** [review]
I have not manually rechecked if you hit the requested code coverage goals but I ran the tests and they all passed fine.
I also think the tests are written in a clean way.

**Comment by RinorSefa** [comment]
I think this commit should be divided into smaller logical commits, also we should use a descriptive commit msg. Open for discussion

**Comment by jvdassen** [comment]
I see what @RinorSefa means - I guess from the point of view of the maintainers of the project his proposal makes sense. Right now it would be hard to see exactly what change is introduced - if we had a commit message like "Test edge cases in the Sentence class" one would immediately see what does change does

**Comment by julwil** [comment]
@RinorSefa @jvdassen Thanks guys, I split the commit in 2

**Pull request merged**
